services:
  
  backend:
    build: backend
    container_name: backend
    command: uvicorn backend.main:app --host 0.0.0.0 --port 80 --reload --reload-include *.yaml
    ports:
      - 8000:80
    volumes:
      - .:/backend
  
  # scraper:
  #   build: scraper
  #   container_name: scraper
  #   command: python start_scraping.py
  #   volumes:
  #     - .:/scraper
