"""init

Revision ID: 179d54865e68
Revises: 
Create Date: 2022-10-18 11:33:01.553434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179d54865e68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('competition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('standing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('standing_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['standing_id'], ['standing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('position')
    op.drop_table('standing')
    op.drop_table('competition')
    # ### end Alembic commands ###
