"""Added model fields

Revision ID: 23e85f547712
Revises: 179d54865e68
Create Date: 2022-10-18 11:53:51.418087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e85f547712'
down_revision = '179d54865e68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('position', sa.Integer(), nullable=True))
    op.add_column('position', sa.Column('team', sa.String(), nullable=True))
    op.add_column('position', sa.Column('won', sa.Integer(), nullable=True))
    op.add_column('position', sa.Column('draw', sa.Integer(), nullable=True))
    op.add_column('position', sa.Column('points', sa.String(), nullable=True))
    op.add_column('position', sa.Column('goal_difference', sa.Integer(), nullable=True))
    op.add_column('position', sa.Column('goals_for', sa.Integer(), nullable=True))
    op.add_column('position', sa.Column('goals_against', sa.Integer(), nullable=True))
    op.add_column('standing', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('standing', 'updated_at')
    op.drop_column('position', 'goals_against')
    op.drop_column('position', 'goals_for')
    op.drop_column('position', 'goal_difference')
    op.drop_column('position', 'points')
    op.drop_column('position', 'draw')
    op.drop_column('position', 'won')
    op.drop_column('position', 'team')
    op.drop_column('position', 'position')
    # ### end Alembic commands ###
