"""added forgotten model fields

Revision ID: 2c7dcc1d408a
Revises: 23e85f547712
Create Date: 2022-10-18 12:40:31.446336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c7dcc1d408a'
down_revision = '23e85f547712'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('position', sa.Column('played_games', sa.Integer(), nullable=True))
    op.add_column('position', sa.Column('lost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('position', 'lost')
    op.drop_column('position', 'played_games')
    # ### end Alembic commands ###
