

[handball_bl]
    testing = true
    url = "https://www.liquimoly-hbl.de/de/liqui-moly-hbl/tabelle/saisonen/tabelle/saison-22-23/gesamt-tabelle/"
    
    # inspect the site for xpath of table item 
    xpath = '//*[@id="standings2028776"]/div/table/tbody'
