handball_bl:
  url: "https://www.liquimoly-hbl.de/de/liqui-moly-hbl/spielplan/saisonen/spielplan/saison-23-24/spielplan-chronologisch/"
  offline_filename: "offline_html_bundesliga.txt"

handball_cl:
  url: "https://ehfcl.eurohandball.com/men/2023-24/matches/"
  offline_filename: "offline_html_championsleague.txt"
