

[handball_bl]
    testing = false
    url = "https://www.liquimoly-hbl.de/de/liqui-moly-hbl/spielplan/saisonen/spielplan/saison-23-24/spielplan-nach-spieltagen/"
    
    # inspect the site for xpath of table item 
    xpath = '//*[@id="schedule2164892"]'
