services:
  app:
    build: .
    container_name: sports-webserver
    command: uvicorn main:app --host 0.0.0.0 --port 80 --reload --reload-include *.yaml
    ports:
      - 8000:80
    volumes:
      - .:/app